# Generated by Django 5.0.6 on 2024-06-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrators', '0001_initial'),
        ('Associations', '0002_alter_association_events'),
        ('Contributions', '0001_initial'),
        ('Events', '0003_event_association'),
        ('Members', '0005_member_logged_in_association_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='admins',
            field=models.ManyToManyField(blank=True, to='Administrators.administrator'),
        ),
        migrations.AlterField(
            model_name='association',
            name='contributions',
            field=models.ManyToManyField(blank=True, to='Contributions.eventcontribution'),
        ),
        migrations.AlterField(
            model_name='association',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='associated_events', to='Events.event'),
        ),
        migrations.AlterField(
            model_name='association',
            name='logo',
            field=models.ImageField(upload_to='associations/logos'),
        ),
        migrations.AlterField(
            model_name='association',
            name='members',
            field=models.ManyToManyField(blank=True, to='Members.member'),
        ),
    ]
