# Generated by Django 5.0.6 on 2024-06-15 21:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Associations', '0003_alter_association_admins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='registration_code',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
