# Generated by Django 5.0.6 on 2024-06-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Associations', '0004_association_registration_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='rel_account',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
