# Generated by Django 5.0.6 on 2024-06-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Associations', '0006_alter_association_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='minimum_monthly_savings',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
