# Generated by Django 5.0.6 on 2024-06-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Associations', '0009_association_savings'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
