# Generated by Django 5.0.6 on 2024-06-21 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Associations', '0010_association_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='association',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='association',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
