# Generated by Django 5.0.6 on 2024-06-21 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Associations', '0011_association_address_association_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='registration_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
