# Generated by Django 5.0.6 on 2024-06-21 18:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Associations', '0012_association_registration_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='registration_code_paid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
