# Generated by Django 5.0.6 on 2024-06-15 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Associations', '0002_alter_association_events'),
        ('Events', '0002_event_minimum_contribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='association',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_associated', to='Associations.association'),
        ),
    ]
