# Generated by Django 5.0.6 on 2024-06-15 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_event_association'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
    ]
