# Generated by Django 5.0.6 on 2024-06-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contributions', '0001_initial'),
        ('Events', '0005_remove_event_date_remove_event_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='contributions',
            field=models.ManyToManyField(blank=True, related_name='event_contributions', to='Contributions.eventcontribution'),
        ),
    ]
