# Generated by Django 5.0.6 on 2024-06-25 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0009_event_minimum_contribution_kes'),
        ('Members', '0018_alter_member_current_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('event_type', models.CharField(blank=True, choices=[('Administrative', 'Administrative'), ('Condolences', 'Condolences'), ('Medical', 'Medical')], max_length=100, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_events', to='Members.member')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='events', to='Events.personalevent'),
        ),
    ]
