# Generated by Django 5.0.6 on 2024-06-25 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0010_personalevent_event_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='events',
        ),
    ]
