# Generated by Django 5.0.6 on 2024-06-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0014_personalevent_contributions_personalevent_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalevent',
            name='minimum_contribution',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalevent',
            name='event_type',
            field=models.CharField(blank=True, choices=[('Birthday', 'Birthday'), ('Anniversary', 'Anniversary'), ('Condolences', 'Condolences'), ('Wedding', 'Wedding')], max_length=100, null=True),
        ),
    ]
