# Generated by Django 5.0.6 on 2024-06-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0015_personalevent_minimum_contribution_and_more'),
        ('Pledges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalevent',
            name='pledges',
            field=models.ManyToManyField(blank=True, related_name='personal_events', to='Pledges.pledge'),
        ),
    ]
