# Generated by Django 5.0.6 on 2024-06-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pledges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='names',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
