# Generated by Django 5.0.6 on 2024-06-16 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Savings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saving',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Savings.savingtarget'),
        ),
    ]
