# Generated by Django 5.0.6 on 2024-06-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Savings', '0004_savingtarget_association'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingtarget',
            name='savings',
            field=models.ManyToManyField(blank=True, to='Savings.saving'),
        ),
    ]
