# Generated by Django 5.0.6 on 2024-06-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Savings', '0006_saving_reference_saving_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingtarget',
            name='target_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
