# Generated by Django 5.0.6 on 2024-06-19 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Savings', '0008_normalsaving'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saving',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Savings.savingtarget'),
        ),
    ]
