# Generated by Django 5.0.6 on 2024-06-19 21:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Savings', '0009_alter_saving_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalsaving',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
