# Generated by Django 5.0.6 on 2024-06-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Savings', '0011_normalsaving_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingtarget',
            name='starting_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
