# Generated by Django 5.0.6 on 2024-06-20 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Savings', '0012_savingtarget_starting_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingtarget',
            name='starting_amount',
        ),
    ]
