# Generated by Django 5.0.6 on 2024-06-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contributions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcontribution',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
