# Generated by Django 5.0.6 on 2024-06-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contributions', '0003_remove_eventcontribution_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcontribution',
            name='reference',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='eventcontribution',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=20),
        ),
    ]
