# Generated by Django 5.0.6 on 2024-06-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contributions', '0004_eventcontribution_reference_eventcontribution_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcontribution',
            name='currency',
            field=models.CharField(blank=True, choices=[('UGX', 'UGX'), ('KES', 'KES')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='eventcontribution',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
