# Generated by Django 5.0.6 on 2024-06-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contributions', '0007_personaleventcontribution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaleventcontribution',
            name='user',
        ),
        migrations.AddField(
            model_name='personaleventcontribution',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
