# Generated by Django 5.0.6 on 2024-06-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contributions', '0008_remove_personaleventcontribution_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaleventcontribution',
            name='names',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
