# Generated by Django 5.0.6 on 2024-06-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biodata', '0002_biodata_company_or_business_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
