# Generated by Django 5.0.6 on 2024-06-19 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Biodata', '0003_alter_biodata_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biodata',
            name='dependents',
        ),
    ]
