# Generated by Django 5.0.6 on 2024-06-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biodata', '0004_remove_biodata_dependents'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodata',
            name='dependents',
            field=models.ManyToManyField(blank=True, related_name='biodata_dependents', to='Biodata.dependent'),
        ),
    ]
