# Generated by Django 5.0.6 on 2024-06-20 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biodata', '0005_biodata_dependents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependent',
            name='member',
        ),
        migrations.AddField(
            model_name='dependent',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='dependent',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dependent',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dependent',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
