# Generated by Django 5.0.6 on 2024-06-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biodata', '0008_dependent_date_of_birth_dependent_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependent',
            name='relationship',
            field=models.CharField(blank=True, choices=[('Spouse', 'Spouse'), ('Child', 'Child'), ('Sibling', 'Sibling'), ('Parent', 'Parent'), ('Parent-in-law', 'Parent-in-law')], max_length=100, null=True),
        ),
    ]
