# Generated by Django 5.0.6 on 2024-06-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biodata', '0010_alter_biodata_employment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodata',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
