# Generated by Django 5.0.6 on 2024-06-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed')], default='Active', max_length=10),
        ),
        migrations.AlterField(
            model_name='poll',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
