# Generated by Django 5.0.6 on 2024-06-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0009_alter_member_picture'),
        ('Polls', '0004_poll_association'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='voters',
            field=models.ManyToManyField(related_name='polls', to='Members.member'),
        ),
    ]
