# Generated by Django 5.0.6 on 2024-06-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0011_member_verification_code'),
        ('Polls', '0005_poll_voters'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='agm_attendees',
            field=models.ManyToManyField(blank=True, related_name='agm_polls', to='Members.member'),
        ),
    ]
