# Generated by Django 5.0.6 on 2024-06-14 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Associations', '0001_initial'),
        ('Members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('repayment_date', models.DateField(blank=True, null=True)),
                ('repaid_at', models.DateTimeField(blank=True, null=True)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Associations.association')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Members.member')),
            ],
        ),
    ]
