# Generated by Django 5.0.6 on 2024-06-16 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanRequests', '0001_initial'),
        ('Loans', '0002_loan_guarantors'),
        ('Members', '0009_alter_member_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanrequest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='loanrequest',
            name='interest_rate',
        ),
        migrations.RemoveField(
            model_name='loanrequest',
            name='repaid_at',
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='guarantors',
            field=models.ManyToManyField(blank=True, related_name='loan_request_guarantors', to='Members.member'),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='loan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Loans.loan'),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
