# Generated by Django 5.0.6 on 2024-06-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanRequests', '0002_remove_loanrequest_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='applied_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
