# Generated by Django 5.0.6 on 2024-06-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanRequests', '0003_loanrequest_applied_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='recieving_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
