# Generated by Django 5.0.6 on 2024-06-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanRequests', '0004_loanrequest_recieving_number'),
        ('Members', '0011_member_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='approved_guarantors',
            field=models.ManyToManyField(blank=True, related_name='loan_request_approved_guarantors', to='Members.member'),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('waiting for guarantors', 'Waiting for guarantors')], default='waiting for guarantors', max_length=50),
        ),
    ]
