# Generated by Django 5.0.6 on 2024-06-21 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanRequests', '0005_loanrequest_approved_guarantors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='reference',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
