# Generated by Django 5.0.6 on 2024-06-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Suspensions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspension',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Ended', 'Ended')], default='Active', max_length=10),
        ),
    ]
