# Generated by Django 5.0.6 on 2024-06-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loans', '0001_initial'),
        ('Members', '0009_alter_member_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='guarantors',
            field=models.ManyToManyField(blank=True, related_name='loan_guarantors', to='Members.member'),
        ),
    ]
