# Generated by Django 5.0.6 on 2024-06-17 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Loans', '0002_loan_guarantors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='status',
        ),
    ]
