# Generated by Django 5.0.6 on 2024-06-17 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loans', '0003_remove_loan_status'),
        ('Members', '0009_alter_member_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='Loans.loan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Members.member')),
            ],
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_repayments',
            field=models.ManyToManyField(blank=True, related_name='loans', to='Loans.loanrepayment'),
        ),
    ]
