# Generated by Django 5.0.6 on 2024-06-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loans', '0005_loan_association'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrepayment',
            name='reference',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=20),
        ),
    ]
