# Generated by Django 5.0.6 on 2024-06-17 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loans', '0006_loanrepayment_reference_loanrepayment_status'),
        ('Members', '0009_alter_member_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrepayment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Members.member'),
        ),
    ]
