# Generated by Django 5.0.6 on 2024-06-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loans', '0009_alter_loanrepayment_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='minimum_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
