# Generated by Django 5.0.6 on 2024-06-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Withdraws', '0002_withdraw_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='reason_for_rejection',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
