# Generated by Django 5.0.6 on 2024-06-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0002_member_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
