# Generated by Django 5.0.6 on 2024-06-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Associations', '0001_initial'),
        ('Members', '0003_member_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='associations',
            field=models.ManyToManyField(blank=True, to='Associations.association'),
        ),
    ]
