# Generated by Django 5.0.6 on 2024-06-15 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Associations', '0001_initial'),
        ('Members', '0004_member_associations'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='logged_in_association',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_logged_in', to='Associations.association'),
        ),
        migrations.AlterField(
            model_name='member',
            name='associations',
            field=models.ManyToManyField(blank=True, related_name='member_associations', to='Associations.association'),
        ),
    ]
