# Generated by Django 5.0.6 on 2024-06-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0006_member_is_admin'),
        ('Savings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='savings',
            field=models.ManyToManyField(blank=True, related_name='member_savings', to='Savings.saving'),
        ),
    ]
