# Generated by Django 5.0.6 on 2024-06-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contributions', '0001_initial'),
        ('Members', '0007_member_savings'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='contributions',
            field=models.ManyToManyField(blank=True, related_name='member_contributions', to='Contributions.eventcontribution'),
        ),
    ]
