# Generated by Django 5.0.6 on 2024-06-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0008_member_contributions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='Members/profile_pictures/'),
        ),
    ]
