# Generated by Django 5.0.6 on 2024-06-17 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0009_alter_member_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
