# Generated by Django 5.0.6 on 2024-06-17 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0010_member_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='verification_code',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
