# Generated by Django 5.0.6 on 2024-06-18 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0011_member_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='current_mode',
            field=models.CharField(choices=[('Member', 'Member'), ('Admin', 'Admin')], default='Member', max_length=10),
        ),
    ]
