# Generated by Django 5.0.6 on 2024-06-19 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biodata', '0001_initial'),
        ('Members', '0012_member_current_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='biodata',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_biodata', to='Biodata.biodata'),
        ),
    ]
