# Generated by Django 5.0.6 on 2024-06-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0013_member_biodata'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='declaration',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
