# Generated by Django 5.0.6 on 2024-06-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0015_remove_member_is_admin_member_registered_by'),
        ('Suspensions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='suspensions',
            field=models.ManyToManyField(blank=True, related_name='member_suspensions', to='Suspensions.suspension'),
        ),
    ]
